### PR TITLE
[1.7] Fix extra http headers

### LINKED ISSUE #404: Not working custom headers
```
require_once 'vendor/autoload.php';

use HeadlessChromium\BrowserFactory;

$browserFactory = new BrowserFactory();
$browser = $browserFactory->createBrowser([
    'windowSize' => [1920, 1080],
    'enableImages' => true,
    'headless' => false,
    'headers' => [
        'Accept: */*',
        'sec-fetch-dest: document',
        //'test' => 'document', // or this
    ]
]);
$page = $browser->createPage();
$page->navigate('http://foxtools.ru/Http');
sleep(20);
$browser->close();

exit();
```

### PR DESCRIPTION
**Pull request by enricodias**
The correct syntax is `['headers' => $headers]`.
`Network.setHTTPHeaders` must be sent per page instance, after `Network.enable`.

`Page::setExtraHTTPHeaders` will now throw an exception if the response contains an error. The tests were modified to actually try to send the headers to chrome, to make them fail if we get an exception.

Fixes  #404

### CODE REVIEW

File: src/Browser.php [hunk 1]
```diff
@@ -186,11 +182,9 @@ public function getTargets()
     }
 
     /**
-     * @param string $targetId
-     *
-     * @return Page|null
+     * @throws CommunicationException
      */
-    public function getPage($targetId)
+    public function getPage(string $targetId): ?Page
```
Comment (GrahamCampbell) [inline src/Browser.php]: this is a major breaking change. we can't add param types to public methods, and can't add return types to public or protected methods on non-final classes

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
